### ISSUE TITLE
Using docker-compose exec throw SouldNoHappen Exception

### ISSUE THREAD

**Issue by jeremynikolic** [pestphp/pest-intellij#116]
Hi 👋 ,

In phpstorm I am using a remote docker interpreter for PHP. My host machine is windows and I am running a docker setup based on laradock with php 8.

Jetbrains recently changed the lifecycle option for it, therefore I may use the "docker-compose exec" option now instead of "docker-compose run".

Tests are running fine with the later but are failing to run with the former, because of test file not being found::
```
- Issue: Test file not found.
- PHP version: 8.0.2
- Operating system: Linux

  at platform/vendor/pestphp/pest/src/Exceptions/ShouldNotHappen.php:38
     34▕      * Creates a new instance of should not happen without a specific exception.
     35▕      */
     36▕     public static function fromMessage(string $message): ShouldNotHappen
     37▕     {
  ➜  38▕         return new ShouldNotHappen(new Exception($message));
     39▕     }
     40▕ }
     41▕
```

Here is the final command that is ran by phpstorm ('platform' being where my project sits):
```
[docker-compose://[C:\...\docker-compose.yml]:workspace/]:php /var/www/platform/vendor/bin/pest --teamcity --configuration /var/www/platform/phpunit.xml /var/www/platform/tests/Unit
```
I've tried different cases all returning the same error: test folder, test file, individual test, defined in the config file. 
Path mappings are all correct, pest executable too.

Reverting to "docker-compose run" still works fine.

Let me know if I can provide more infos and test other cases

**Comment by olivernybroe** [comment]
Did you ever resolve this or still having this issue?

**Comment by jeremynikolic** [comment]
I haven't tried this for a month or two but there's been some updates to phpstom. I'll see if this keeps happening and report back 👍

**Comment by jeremynikolic** [comment]
Given this another go with newest PHPStorm 2021.2 and same happens 😢 

I've given this a try with some PHPUnit tests which are all running well.

I'll give another try to setting up the dev environnement and dig into this

**Comment by j-dexx** [comment]
I've got the same issue.

> [docker-compose://[/Users/james/www/internal-api/docker-compose.yml]:internal-api/]:php /var/www/html/vendor/bin/pest --teamcity --configuration /var/www/html/phpunit.xml
Testing started at 12:28 ...
Creating internal-api_internal-api_run ... 
Creating internal-api_internal-api_run ... done
   Pest\Exceptions\ShouldNotHappen 

- Issue: Test file not found.

If I copy the command being run into a bash shell within the container it'll work
`php /var/www/html/vendor/bin/pest --teamcity --configuration /var/www/html/phpunit.xml`

Both via phpstorm and directly in the container I see the same content when var_dumping `$testSuite` in `pest.php`

>  ["rootPath"]=>
  string(13) "/var/www/html"
  ["testPath"]=>
  string(5) "tests" 

So the rootPath is set correctly to where in the docker container my code is.

**Comment by ppmathis** [comment]
I've been facing the same issue today when attempting to configure PHPStorm to properly run Pest tests inside a Docker environment provided by Laravel Sail.

<details>
<summary><b>Log output from failed run with <code>ShouldNotHappen</code> exception</b></summary>

```
[docker-compose://[/Users/ppmathis/Developer/xxx/docker-compose.yml]:laravel.test/]:php /var/www/html/vendor/pestphp/pest/bin/pest --teamcity --configuration /var/www/html/phpunit.xml
WARN[0000] The "WWWUSER" variable is not set. Defaulting to a blank string. 
WARN[0000] The "WWWGROUP" variable is not set. Defaulting to a blank string. 
[+] Running 3/0
 ⠿ Container xxx-redis-1    Running 0.0s
 ⠿ Container xxx-mailhog-1  Running 0.0s
 ⠿ Container xxx-mariadb-1  Running 0.0s

   Pest\Exceptions\ShouldNotHappen 

  
This should not happen - please create an new issue here: https://github.com/pestphp/pest.

- Issue: Test file not found.
- PHP version: 8.1.12
- Operating system: Linux

  at /var/www/html/vendor/pestphp/pest/src/Exceptions/ShouldNotHappen.php:38
     34▕      * Creates a new instance of should not happen without a specific exception.
     35▕      */
     36▕     public static function fromMessage(string $message): ShouldNotHappen
     37▕     {
  ➜  38▕         return new ShouldNotHappen(new Exception($message));
     39▕     }
     40▕ }
     41▕ 

      +3 vendor frames 
  4   /var/www/html/tests/Feature/TagTest.php:13
      it()

Process finished with exit code 1
```

</details>

A quick string search for `Test file not found.` led me towards [`src/Support/Backtrace.php`](https://github.com/pestphp/pest/blob/6a3cc48d6b11493e3488fc24874680877b32f6a2/src/Support/Backtrace.php#L24-L45) of the Pest framework, which attempts to walk through the backtrace until it finds the file right above its own `FileLoader`, which will be the actual file to be tested.

Adding a couple debug statements around this section quickly revealed the issue behind this very exotic error, which is that somehow my current working directory was set to `/opt/project` by PHPStorm / IDEA, despite all mappings being properly set up using `/var/www/html`. As said directory does not exist within Laravel Sail container, this causes the following conditional to misbehave:

```php
if (Str::endsWith($trace[self::FILE], (string) realpath('vendor/phpunit/phpunit/src/Util/FileLoader.php'))) {
```

This is due to `realpath()` being unable to find `vendor/phpunit/phpunit/src/Util/FileLoader.php` within the current working directory, as `/opt/project/vendor/phpunit/phpunit/src/Util/FileLoader.php` does obviously not exist either. As `realpath()` is forcefully casted without verifying if the command was successful, this ends up turning `false` into an empty string. As every string "ends" with an empty string, this condition will always match and immediately break out of the loop before the proper test file was determined.

I have no idea whatsoever from where PHPStorm / IDEA happens to take this `/opt/project` path despite mapping everything properly, but this is what caused this weird issue for me. Luckily there happens to be an easy workaround, which requires to adjust the configuration of the remote CLI interpreter in the IDE:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/1204969/201497797-f908ad85-4b15-4baf-88a9-dc19b6d442de.png">

The default selection `Always start a new container` causes the incorrect working directory to be used, but given that all the Sail containers are already running locally I could not find a reason to not use `Connect to existing container` instead. The latter also happens to fix this issue, as the running container has the correct working directory `/var/www/html`.

@olivernybroe Maybe you are able to fix this by manually specifying a working directory when launching Pest in your plugin? Although given how the remote CLI interpreters feature is a part of a JetBrains plugin and most likely abstracting this away from other plugins, I'm not fully sure if that is within the scope of your plugin or not.

**Comment by kmuenkel** [comment]
That workaround only works if the docker container's working root may not be the same as your project root.

The directory reference you've identified on there is making two unreliable assumptions:

1. Composer supports an optional "vendor-dir" that may result in PhpUnit _not_ being in the "vendor" folder
2.  PhpUnit won't update in a way that changes the location of `FileLoader`.

A more reliable way to write that line would be to let it all be dynamic:

```
if (Str::endsWith($trace[self::FILE], (new \ReflectionClass(new \PHPUnit\Util\FileLoader))->getFileName())) {
```
