### ISSUE TITLE
An issue directly running tests in a non-standard folder pattern

### ISSUE THREAD

**Issue by Orrison** [pestphp/pest-intellij#486]
**Describe the bug**
It seems a recent update has caused issues with directly running single tests or test files with the Pest plugin. Using a non-standard file system setup like using https://github.com/InterNACHI/modular causes singular test runs to not work. While entire test runs do work.

**To Reproduce**
1. Setup a non-standard project folder structure such as using https://github.com/InterNACHI/modular
2. Add a test within the non-standard folder structure
3. Try and run that single test from within the file

**Expected behavior**
Tests should be able to be run from where ever they are within the folder structure as paths to executables and config files are provided to the plugin

**Screenshots**
https://d.pr/v/jHhr02/PiR6tI6B2X

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - IntelliJ Version: PHPStorm 2023.2
 - Plugin Version 1.10.1

**Comment by olivernybroe** [comment]
Seems more related to running via Laravel Sail vs running locally 🤔

**Comment by Orrison** [comment]
> Seems more related to running via Laravel Sail vs running locally 🤔

I am able to run tests in traditional folders this way also in Sail.

**Comment by olivernybroe** [comment]
Ah just took a quick look at what this setup is about. 

Yes that is not supported and won't be supported because of limitations from PhpStorm.
PhpStorm only supports one composer.json file per project and we rely on the location of it to determine multiple things. 

So until PhpStorm supports multiple composer.json file, we probably won't support it either. 


A workaround would be to open every single composer project as it's own PhpStorm project. Haven't tested it, but I think that might work.
